dict.common <- dictionary(list(Chemiewaffen = c("chemiewaffen","chemiewaffenanschlag","chemiewaffeneinsatz",
                                                "chemiewaffeninspekteur","chemiewaffenkon","chemiewaffenkonven",
                                                "chemiewaffenlag","chemiewaffenprogramm","chemiewaffen?bereinkommen",
                                                "chemiewaffenvernichtung"),
                               Demokratie = c("demokrati","demokratiebewegung",
                                              "demokratiebewegungen","demokratied","demokratiedefi",
                                              "demokratiedefizit","demokratieerziehung","demokratief?rd",
                                              "demokratief?rderung","demokratiegeschicht","demokratiegewinn",
                                              "demokratieklausel","demokratiekonzept","demokratien",
                                              "demokratieprinzip","demokratiesicherung","demokratietheoretischen",
                                              "demokratiev","demokratieverachtung","demokratieverlust",
                                              "demokratieverst?ndni","demokratiewach"),
                               Menschenrecht = c("menschenrecht","menschenrechteinrichtungen",
                                                 "menschenrechten","menschenrechtl","menschenrechtlich",
                                                 "menschenrechtlichen","menschenrechts-check","menschenrechts-t?v",
                                                 "menschenrechtsaktivisten","menschenrechtsanliegen","menschenrechtsansatz",
                                                 "menschenrechtsanw?ltin","menschenrechtsausschuss","menschenrechtsb",
                                                 "menschenrechtsba","menschenrechtsbasi","menschenrechtsbasiert",
                                                 "menschenrechtsbasierten","menschenrechtsbeauftragten","menschenrechtsbericht",
                                                 "menschenrechtsbotschaft","menschenrechtsdefizit","menschenrechtsdia",
                                                 "menschenrechtsdialog","menschenrechtsfeindlich","menschenrechtsfragen",
                                                 "menschenrechtsidyll","menschenrechtsinstitut","menschenrechtsklausel",
                                                 "menschenrechtskommiss","menschenrechtskonven","menschenrechtskonvent",
                                                 "menschenrechtskonventionen","menschenrechtskonzept","menschenrechtslag",
                                                 "menschenrechtslogo","menschenrechtsorganis","menschenrechtsorganisatio",
                                                 "menschenrechtsorganisationen","menschenrechtspartei","menschenrechtspol",
                                                 "menschenrechtspoli","menschenrechtspolitik","menschenrechtspreis",
                                                 "menschenrechtsrat","menschenrechtsschutz","menschenrechtsschutzsystem",
                                                 "menschenrechtssi","menschenrechtssitu","menschenrechtsstandard",
                                                 "menschenrechtsstiftung","menschenrechtssystem","menschenrechtsv",
                                                 "menschenrechtsverlet","menschenrechtsverletzun","menschenrechtsverletzung",
                                                 "menschenrechtsverletzungen","menschenrechtsverteidig","menschenrechtsverteidigerinnen",
                                                 "menschenrechtswidrig"),
                               Strafverfolgung = c("strafverfolgung","strafverfolgungsbeh?r","strafverfolgungsbeh?rden",
                                                   "strafverfolgungsma?nahmen","strafverfolgungsor","strafverfolgungsstatistik",
                                                   "strafverfolgungsstatistiken"),
                               Verteidigung = c("verteidigung",
                                                "verteidigungsagentur","verteidigungsauftrag","verteidigungsaus",
                                                "verteidigungsausschuss","verteidigungsbegriff","verteidigungsbereich",
                                                "verteidigungsbud","verteidigungsbudget","verteidigungsb?ndni",
                                                "verteidigungsetat","verteidigungsfal","verteidigungsfragen",
                                                "verteidigungshaus","verteidigungshaushalt","verteidigungsidentit?t",
                                                "verteidigungsmi","verteidigungsmini","verteidigungsminist",
                                                "verteidigungsministerin","verteidigungsministerium","verteidigungsnotwendigkeit",
                                                "verteidigungspol","verteidigungspoli","verteidigungspolitik",
                                                "verteidigungspolitikern","verteidigungspolitisch","verteidigungspolitischen")))

dict.divisive<-dictionary(list(
  Inflation = c("inflat",
                "inflation?r","inflation?ren","inflationsbereinigt",
                "inflationsdruck","inflationsr","inflationsziel"),
  Krankenversicherung = c("krankenversicherung","krankenversicherungen","krankenversicherungspflicht",
                          "krankenversicherungsschutz"),
  Mindestlohn = c("mindestlohn","mindestlohnbasi",
                  "mindestlohndebatt","mindestlohnforderung","mindestlohngesetz",
                  "mindestlohnjob","mindestlohnkommiss","mindestlohnkonzept",
                  "mindestlohnniveau","mindestlohnreg","mindestlohntarifvertrag",
                  "mindestlohnvorschl?g"),
  Sozialversicherung = c(
    "sozialversicherung","sozialversicherungen",
    "sozialversicherungsbei","sozialversicherungsbeitrag","sozialversicherungsbeitr?g",
    "sozialversicherungsbeitr?gen","sozialversicherungsein","sozialversicherungspflich",
    "sozialversicherungspflichtig","sozialversicherungspflichtigen","sozialversicherungsrecht",
    "sozialversicherungssystem"),
  Steuererhohung = c("steuererh?hung",
                     "steuererh?hungen","steuererh?hungskorsett","steuererh?hungsor")))